// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Inventory struct {
	InventoryID      string              `json:"InventoryId"`
	Name             string              `json:"Name"`
	Count            int                 `json:"Count"`
	Price            float64             `json:"Price"`
	ExpirationDate   string              `json:"ExpirationDate"`
	Site             string              `json:"Site"`
	SkuNumber        string              `json:"SkuNumber"`
	InventoryVitamin []*InventoryVitamin `json:"InventoryVitamin"`
}

type InventoryConsumed struct {
	Name        string `json:"Name"`
	Amount      int    `json:"Amount"`
	Measurement string `json:"Measurement"`
}

type InventoryToUpdate struct {
	ID             string  `json:"Id"`
	Name           string  `json:"Name"`
	Count          int     `json:"Count"`
	Price          float64 `json:"Price"`
	ExpirationDate string  `json:"ExpirationDate"`
	Site           string  `json:"Site"`
	SkuNumber      string  `json:"SkuNumber"`
}

type InventoryVitamin struct {
	InventoryVitaminID string `json:"InventoryVitaminId"`
	InventoryID        int    `json:"InventoryId"`
	VitaminID          int    `json:"VitaminId"`
	PercentDailyValue  int    `json:"PercentDailyValue"`
}

type NewInventory struct {
	ID             string  `json:"Id"`
	Name           string  `json:"Name"`
	Count          int     `json:"Count"`
	Price          float64 `json:"Price"`
	ExpirationDate string  `json:"ExpirationDate"`
	Site           string  `json:"Site"`
	SkuNumber      string  `json:"SkuNumber"`
}

type NewInventoryResponse struct {
	ID             string  `json:"Id"`
	Name           string  `json:"Name"`
	Count          int     `json:"Count"`
	Price          float64 `json:"Price"`
	ExpirationDate string  `json:"ExpirationDate"`
	Site           string  `json:"Site"`
	SkuNumber      string  `json:"SkuNumber"`
}

type NutritionFact struct {
	Vitamin string `json:"Vitamin"`
	Percent int    `json:"Percent"`
}

type NutritionFacts struct {
	InventoryName string         `json:"InventoryName"`
	NutritionFact *NutritionFact `json:"NutritionFact"`
}
